language: python
sudo: required


python:
  - '3.6'
  - '3.5'

matrix:
  include:
    - python: '3.6'
      env: AIOHTTP_MASTER="y"

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -r requirements-dev.txt
    - pip install https://github.com/aio-libs/aiohttp/archive/master.zip
    - |
        if [ "$AIOHTTP_MASTER" = "y" ]; then
            pip install https://github.com/aio-libs/aiohttp/archive/master.zip
        fi;

script:
    make cov
after_success:
    codecov
